# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: R
r:
  - oldrel
  - release
sudo: false
os:
- osx
- linux
cache: packages
r_packages:
  - covr
before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libudunits2-dev; fi
install:
- R -e 'install.packages("devtools", repos = "http://cran.rstudio.com")'
- R -e 'devtools::install_deps(dep = T)'
compiler: gcc
script:
- travis_wait R CMD build .
- travis_wait R CMD check *tar.gz
after_success:
- R -e 'library(covr); codecov()'